# Generated by Django 6.0 on 2025-12-12 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(default='Kolkata, West Bengal, India', max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Project/Work/Position name', max_length=200)),
                ('organization', models.CharField(blank=True, help_text='Company/Organization (optional)', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Higher number appears first')),
            ],
            options={
                'verbose_name': 'Experience/Project',
                'verbose_name_plural': 'Experiences/Projects',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='One point description')),
                ('order', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Portfolio.experience')),
            ],
            options={
                'verbose_name': 'Description Point',
                'verbose_name_plural': 'Description Points',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='Portfolio.experience')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Tech Stack',
                'ordering': ['order'],
            },
        ),
    ]
