# Generated by Django 6.0 on 2025-12-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedetail',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
