# Generated by Django 6.0 on 2025-12-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_experiencedetail_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedetail',
            name='project_link',
        ),
        migrations.AddField(
            model_name='experience',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
